import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

function readRepoFile(relativePath: string) {
  return readFileSync(path.join(repoRoot, relativePath), "utf8");
}

describe("backend S10 contract", () => {
  it("declares MySQL persistence for S10 budget structures", () => {
    const sql = readRepoFile("sql/mysql/001_mtrd_itemicostos_real.sql");

    expect(sql).toContain("MTRD_PresupuestoConfig");
    expect(sql).toContain("MTRD_ItemMetrado");
    expect(sql).toContain("MTRD_GrupoPolinomico");
    expect(sql).toContain("MTRD_RecursoCatalogo_GrupoPolinomicoUID");
    expect(sql).toContain("MTRD_ItemApuInsumo_SubpartidaUID");
  });

  it("keeps the Revit import/export endpoints and compact row fields", () => {
    const server = readRepoFile("server.js");
    const sql = readRepoFile("sql/mysql/001_mtrd_itemicostos_real.sql");
    const revitImportDomain = readRepoFile("src/application/budget/bim-revit-import-domain.mjs");
    const revitExportDomain = readRepoFile("src/application/budget/bim-revit-export-domain.mjs");

    expect(server).toContain("/api/revit/import-state");
    expect(server).toContain("/api/revit/export");
    expect(server).toContain("bim-revit-import-domain.mjs");
    expect(server).toContain("buildRevitImportStateFromStateDomain");
    expect(server).toContain("normalizeRevitImportRows");
    expect(server).toContain("normalizeIncomingRevitExport");
    expect(server).toContain("bim-revit-export-domain.mjs");
    expect(server).toContain("codigoPartida");
    expect(server).toContain("codificacion");
    expect(server).toContain("descripcion");
    expect(server).toContain("unidad");
    expect(server).toContain("costo");
    expect(server).toContain("formula-polinomica");
    expect(server).toContain("ingestRevitExport");
    expect(server).toContain("MTRD_Item_MetradoBim");
    expect(server).toContain("MTRD_RevitExport");
    expect(server).toContain("MTRD_RevitExportItem");
    expect(sql).toContain("MTRD_RevitExport");
    expect(sql).toContain("MTRD_RevitExportItem");
    expect(revitImportDomain).toContain("buildRevitImportStateFromState");
    expect(revitImportDomain).toContain("REVIT_IMPORT_ROW_FIELDS");
    expect(revitImportDomain).toContain("codigoPartida");
    expect(revitImportDomain).toContain("codificacion");
    expect(revitImportDomain).toContain("descripcion");
    expect(revitImportDomain).toContain("unidad");
    expect(revitImportDomain).toContain("costo");
    expect(revitExportDomain).toContain("normalizeIncomingRevitExport");
    expect(revitExportDomain).toContain("syncItemMetradoBim");
    expect(revitExportDomain).toContain("source.rows");
    expect(revitExportDomain).toContain("source.items");
    expect(revitExportDomain).toContain("source.projectUid");
    expect(revitExportDomain).toContain("source.metradoBim");
  });

  it("declares BIM job queue persistence and bridge endpoints", () => {
    const sql = readRepoFile("sql/mysql/001_mtrd_itemicostos_real.sql");
    const server = readRepoFile("server.js");
    const workspace = readRepoFile("src/features/workspace/QuantivaWorkspace.tsx");
    const bimJobsDomain = readRepoFile("src/application/budget/bim-jobs-domain.ts");
    const styles = readRepoFile("styles.css");
    const apiSmoke = readRepoFile("workers/bim-api-smoke.mjs");
    const bridgeE2eSmoke = readRepoFile("workers/bim-bridge-e2e-smoke.mjs");
    const smokeConfig = readRepoFile("workers/bim-smoke-config.mjs");
    const smokeConfigDomain = readRepoFile("workers/bim-smoke-config-domain.mjs");
    const cloudWorker = readRepoFile("workers/bim-cloud-worker.mjs");
    const cloudWorkerDomain = readRepoFile("workers/bim-cloud-worker-domain.mjs");
    const realtimeLoadTest = readRepoFile("workers/bim-realtime-load-test-domain.mjs");
    const fluencyCheck = readRepoFile("workers/bim-fluency-check.mjs");
    const fluencyCheckDomain = readRepoFile("workers/bim-fluency-check-domain.mjs");
    const readiness = readRepoFile("workers/bim-readiness-domain.mjs");
    const artifactDomain = readRepoFile("src/application/budget/bim-artifact-domain.mjs");
    const bridgeAccessDomain = readRepoFile("src/application/budget/bim-bridge-access-domain.mjs");
    const jobEventsDomain = readRepoFile("src/application/budget/bim-job-events-domain.mjs");
    const jobQueryDomain = readRepoFile("src/application/budget/bim-job-query-domain.mjs");
    const jobStateDomain = readRepoFile("src/application/budget/bim-job-state-domain.mjs");
    const jobCommandDomain = readRepoFile("src/application/budget/bim-job-command-domain.mjs");
    const bridgePresenceDomain = readRepoFile("src/application/budget/bim-bridge-presence-domain.mjs");
    const applyPlanDomain = readRepoFile("src/application/budget/bim-apply-plan-domain.mjs");
    const modelIdentityDomain = readRepoFile("src/application/budget/bim-job-model-identity-domain.mjs");
    const ownershipDomain = readRepoFile("src/application/budget/bim-job-ownership-domain.mjs");
    const operationsDomain = readRepoFile("src/application/budget/bim-job-operations-domain.mjs");
    const packageJson = readRepoFile("package.json");
    const revitBenchmarkProgram = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Benchmarks/Program.cs");
    const revitBenchmarkProject = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Benchmarks/RevitModelAudit.Benchmarks.csproj");
    const revitBridgeBackoffPlanner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobBridgeBackoffPlanner.cs");

    expect(sql).toContain("MTRD_BimJob");
    expect(sql).toContain("MTRD_BimJobLog");
    expect(sql).toContain("MTRD_BimJobArtifact");
    expect(sql).toContain("MTRD_BimJobCache");
    expect(sql).toContain("MTRD_BimJobOperation");
    expect(sql).toContain("MTRD_BimBridgeHeartbeat");
    expect(sql).toContain("UQ_MTRD_BimBridgeHeartbeat_Bridge_Project_User");
    expect(sql).toContain("UQ_MTRD_BimJobOperation_Job_Source_Order");
    expect(sql).toContain("MTRD_BimJob_ModelKeyHash");
    expect(sql).toContain("IX_MTRD_BimJob_Reutilizable");
    expect(server).toContain("/api/bim/jobs");
    expect(server).toContain("/api/bim/readiness");
    expect(server).toContain("createBackendBimReadinessSnapshot");
    expect(server).toContain("resolveRequestBaseUrl");
    expect(server).toContain("/api/bim/jobs/summary");
    expect(server).toContain("getBimJobQueueSummary");
    expect(server).toContain("mapBimJobQueueSummaryRows");
    expect(server).toContain("activeRevitQueued");
    expect(server).toContain("oldestActiveRevitQueuedAgeSeconds");
    expect(bimJobsDomain).toContain("getBimJobBridgeWaitDiagnostic");
    expect(bimJobsDomain).toContain("bridge-offline");
    expect(bimJobsDomain).toContain("Revit cerrado o bridge detenido");
    expect(workspace).toContain("bim-job-bridge-wait");
    expect(workspace).toContain("bridgeWait.action");
    expect(server).toContain("/api/bim/bridge/commands");
    expect(server).toContain("/api/bim/bridge/summary");
    expect(server).toContain("/api/bim/bridge/heartbeat");
    expect(server).toContain("saveBimBridgeHeartbeat");
    expect(server).toContain("bridgePresence");
    expect(bridgePresenceDomain).toContain("latestDiagnostic");
    expect(bridgePresenceDomain).toContain("bridgeDiagnostic");
    expect(bridgePresenceDomain).toContain("summarizeBimBridgePresence");
    expect(bridgePresenceDomain).toContain("normalizeIncomingBimBridgeHeartbeat");
    expect(server).toContain("const parsed = JSON.parse(text)");
    expect(server).toContain("mapBimBridgeHeartbeatRow");
    expect(bridgeE2eSmoke).toContain("bridge-summary-presence");
    expect(bridgeE2eSmoke).toContain("assertBridgePresence");
    expect(server).toContain("[\"GET\", \"HEAD\"].includes(method)");
    expect(server).toContain("acceptsHtmlFallback");
    expect(server).toContain("targetMode");
    expect(server).toContain("bim-job-command-domain.mjs");
    expect(jobCommandDomain).toContain("normalizeIncomingBimJobCreate");
    expect(jobCommandDomain).toContain("getBimJobTargetCommandIssue");
    expect(jobCommandDomain).toContain("BIM_JOB_TARGET_COMMAND_MISMATCH_MESSAGE");
    expect(jobCommandDomain).toContain("isActiveRevitCommand");
    expect(jobCommandDomain).toContain("isCloudModelCommand");
    expect(jobCommandDomain).toContain("normalizeIncomingBimClaimIdentity");
    expect(jobCommandDomain).toContain("normalizeIncomingBimJobProgress");
    expect(jobCommandDomain).toContain("normalizeBimJobTargetMode");
    expect(jobCommandDomain).toContain("normalizeBimModelPath");
    expect(jobCommandDomain).toContain("activeDocumentVersion");
    expect(jobCommandDomain).toContain("revitDocumentVersion");
    expect(server).toContain("commandTypeFilter");
    expect(server).toContain("normalizeOptionalBimJobCommandType");
    expect(server).toContain("workerId");
    expect(server).toContain("requestedBy");
    expect(server).toContain("Usuario Revit");
    expect(server).toContain("authorizeBimBridgeClaimAccess");
    expect(server).toContain("createBimBridgeClaimAccessDecision");
    expect(server).toContain("allowedProjectIds: bridgeClaimAccess.projectScope.projectIds");
    expect(server).toContain("projectScopeFilter");
    expect(server).toContain("AND p.MTRD_Proyecto_UID IN (?)");
    expect(server).toContain("activeModelIdentity");
    expect(server).toContain("canClaimBimJobForActiveModel");
    expect(server).toContain("getBimJobTargetCommandIssue");
    expect(server.indexOf("const targetCommandIssue = getBimJobTargetCommandIssue(normalized)"))
      .toBeGreaterThan(server.indexOf("normalizeIncomingBimJobCreate(payload)"));
    expect(server.indexOf("const targetCommandIssue = getBimJobTargetCommandIssue(normalized)"))
      .toBeLessThan(server.indexOf("const directApplyIssue = getDirectBimApplyJobCreateIssue(normalized)"));
    expect(workspace).toContain("Jobs BIM Revit");
    expect(workspace).toContain("Revit reporta progreso");
    expect(workspace).toContain("selectActiveRevitReadinessVisibleChecks");
    expect(workspace).toContain("handleCreateActiveRevitJob");
    expect(workspace).not.toContain("onCreateJob(\"cloud-model\")");
    expect(workspace).not.toContain("targetMode === \"cloud-model\"");
    expect(workspace).not.toContain("Cloud worker");
    expect(workspace).not.toContain("worker cloud");
    expect(server).toContain("getDirectBimApplyJobCreateIssue");
    expect(server.indexOf("const directApplyIssue = getDirectBimApplyJobCreateIssue(normalized)"))
      .toBeGreaterThan(server.indexOf("normalizeIncomingBimJobCreate(payload)"));
    expect(server.indexOf("const directApplyIssue = getDirectBimApplyJobCreateIssue(normalized)"))
      .toBeLessThan(server.indexOf("const modelIdentityIssue = getBimJobCreateModelIdentityIssue(normalized)"));
    expect(applyPlanDomain).toContain("BIM_DIRECT_APPLY_JOB_CREATE_MESSAGE");
    expect(applyPlanDomain).toContain("getDirectBimApplyJobCreateIssue");
    expect(applyPlanDomain).toContain("isBimApplyCommand");
    expect(applyPlanDomain).toContain("resolveBimApplyJobBatchSize");
    expect(server).toContain("resolveBimApplyJobBatchSize(previewJob.result?.applyPlan, previewJob.payload)");
    expect(server).not.toContain("function resolveBimApplyBatchSize(payload)");
    expect(server).toContain("getBimJobCreateModelIdentityIssue");
    expect(server.indexOf("const modelIdentityIssue = getBimJobCreateModelIdentityIssue(normalized)"))
      .toBeGreaterThan(server.indexOf("normalizeIncomingBimJobCreate(payload)"));
    expect(server.indexOf("const modelIdentityIssue = getBimJobCreateModelIdentityIssue(normalized)"))
      .toBeLessThan(server.indexOf("storage.createBimJob(normalized"));
    expect(server).toContain("getBimBridgeClaimModelIdentityIssue");
    expect(server.indexOf("const claimModelIdentityIssue = getBimBridgeClaimModelIdentityIssue(targetMode, activeModelIdentity)"))
      .toBeGreaterThan(server.indexOf("authorizeBimBridgeClaimAccess({"));
    expect(server.indexOf("const claimModelIdentityIssue = getBimBridgeClaimModelIdentityIssue(targetMode, activeModelIdentity)"))
      .toBeLessThan(server.indexOf("const jobs = await storage.claimBimJobs({"));
    expect(server).toContain("const shouldFilterByActiveModel = targetMode === \"active-revit\"");
    expect(server).toContain("bim-job-model-identity-domain.mjs");
    expect(modelIdentityDomain).toContain("hasBimClaimModelIdentity");
    expect(modelIdentityDomain).toContain("requiresBimJobCreateModelIdentity");
    expect(modelIdentityDomain).toContain("getBimJobCreateModelIdentityIssue");
    expect(modelIdentityDomain).toContain("getBimBridgeClaimModelIdentityIssue");
    expect(modelIdentityDomain).toContain("BIM_JOB_CREATE_MODEL_IDENTITY_MESSAGE");
    expect(modelIdentityDomain).toContain("BIM_ACTIVE_REVIT_CLAIM_MODEL_IDENTITY_MESSAGE");
    expect(modelIdentityDomain).toContain("parseJsonObject(modelIdentityInput)");
    expect(modelIdentityDomain).toContain("normalizeBimModelPath");
    expect(modelIdentityDomain).toContain("return false");
    expect(modelIdentityDomain).toContain("return comparableKeys > 0");
    expect(server).toContain("bimBridgeProgressRoute");
    expect(server).toContain("bimBridgeOperationsRoute");
    expect(server).toContain("listBimJobOperations");
    expect(server).toContain("replaceBimJobOperations");
    expect(server).toContain("saveBimJobOperationsUpload");
    expect(server).toContain("insertBimJobOperations");
    expect(server).toContain("await connection.beginTransaction()");
    expect(server).toContain("await connection.rollback()");
    expect(server).toContain("normalizeBimJobOperationsUpload");
    expect(server).toContain("detachBimJobOperationsForStorage");
    expect(operationsDomain).toContain("normalizeBimJobOperationsUpload");
    expect(operationsDomain).toContain("planBimJobOperationUploadPages");
    expect(operationsDomain).toContain("operationsSource");
    expect(operationsDomain).toContain("endpoint: `/api/bim/bridge/jobs/${encodeURIComponent(jobUid)}/operations`");
    expect(operationsDomain).toContain("pageSize");
    expect(server).toContain("bimBridgeArtifactsRoute");
    expect(server).toContain("const jobUidForProgress");
    expect(server).toContain("const existingJob = await storage.loadBimJob(jobUidForProgress)");
    expect(server.indexOf("const existingJob = await storage.loadBimJob(jobUidForProgress)"))
      .toBeLessThan(server.indexOf("job = await storage.updateBimJobProgress"));
    expect(server).toContain("saveBimJobArtifacts");
    expect(artifactDomain).toContain("normalizeIncomingBimArtifacts");
    expect(artifactDomain).toContain("decodeBimArtifactContent");
    expect(artifactDomain).toContain("hasBimArtifactContent");
    expect(artifactDomain).toContain("hasBimArtifactReference");
    expect(artifactDomain).toContain("sanitizeBimArtifactName");
    expect(server).toContain("MTRD_BimJob_ClaimedBy AS claimed_by");
    expect(server).toContain("bim-job-ownership-domain.mjs");
    expect(ownershipDomain).toContain("canWriteBimJobArtifactsForClaim");
    expect(ownershipDomain).toContain("canAccessBimJobOperationsForClaim");
    expect(ownershipDomain).toContain("return Boolean(claimedBy && reporterId && claimedBy === reporterId)");
    expect(server).toContain("throw new BimJobOwnershipError(");
    expect(ownershipDomain).toContain("BimJobOwnershipError");
    expect(ownershipDomain).toContain("canReportBimJobProgressForClaim");
    expect(ownershipDomain).toContain("BIM_JOB_OWNERSHIP_MISMATCH");
    expect(server).toContain("MTRD_BimJob_ClaimedBy AS claimed_by");
    expect(server).toContain("canAccessBimJobOperationsForClaim(job.claimedBy, bridgeId)");
    expect(server).toContain("payload?.bridgeId || payload?.workerId || \"revit-bridge\"");
    expect(server).toContain("listBimJobArtifacts");
    expect(server).toContain("loadBimJobArtifact");
    expect(server).toContain("streamBimArtifactDownload");
    expect(server).toContain("BIM_ARTIFACT_ALLOWED_REDIRECT_HOSTS");
    expect(server).toContain("cloud-storage");
    expect(server).toContain("resolveRemoteBimArtifactDownloadUrl");
    expect(server).toContain("normalizeAllowedBimArtifactRedirectUrl");
    expect(server).toContain("isAllowedBimArtifactRedirectHost");
    expect(server).toContain("/download");
    expect(server).toContain("updateBimJobProgress");
    expect(server).toContain("retryBimJob");
    expect(server).toContain("bim-job-query-domain.mjs");
    expect(server).toContain("createBimJobDetailResponse");
    expect(server).toContain("const detailResponse = createBimJobDetailResponse(job)");
    expect(jobQueryDomain).toContain("BIM_JOB_DETAIL_NOT_FOUND_MESSAGE");
    expect(jobQueryDomain).toContain("status: 200");
    expect(jobQueryDomain).toContain("status: 404");
    expect(server).toContain("bim-job-state-domain.mjs");
    expect(server).toContain("createBimJobRetryDecision");
    expect(server).toContain("createBimJobCancelTransition");
    expect(jobStateDomain).toContain("isFinishedBimJobStatus");
    expect(jobStateDomain).toContain("canRetryBimJobStatus");
    expect(jobStateDomain).toContain("canCancelBimJobStatus");
    expect(server).toContain("apply");
    expect(server).toContain("createBimApplyJobFromPreview");
    expect(server).toContain("withBimApplyJobCreationLock");
    expect(server).toContain("buildBimApplyJobCreationLockName");
    expect(server).toContain("loadBimApplyJobForPreview");
    expect(server).toContain("Solicitud duplicada de aplicacion reutilizo el job");
    expect(server).toContain("JSON_UNQUOTE(JSON_EXTRACT(j.MTRD_BimJob_PayloadJson, '$.sourceJobId'))");
    expect(server).toContain("enrichBimJobPayloadForCommand");
    expect(server).toContain("createBimParameterWritePlan");
    expect(server).toContain("loadLatestRevitExportRowsForBimParameterWrites");
    expect(server).toContain("canCreateBimApplyJob");
    expect(server).toContain("canCreateBimApplyJobFromPreviewDomain");
    expect(server).toContain("normalizeBimApplyPlan(previewJob.result?.applyPlan)");
    expect(bimJobsDomain).toContain("hasExecutableBimApplyPlan(job.result.applyPlan)");
    expect(bimJobsDomain).toContain("isBimApplyPlanBoundToPreview(job.result.applyPlan, job.id)");
    expect(bridgeAccessDomain).toContain("BIM_BRIDGE_SESSION_USER_MISMATCH");
    expect(bridgeAccessDomain).toContain("sessionUser.email !== requestedByEmail");
    const bimApplyPlanDomain = readRepoFile("src/application/budget/bim-apply-plan-domain.mjs");
    expect(bimApplyPlanDomain).toContain("const hasPreviewCommand = commandType.includes(\"preview\")");
    expect(bimApplyPlanDomain).toContain("hasExecutableBimApplyPlan(result.applyPlan)");
    expect(bimApplyPlanDomain).toContain("isBimApplyPlanBoundToPreview(result.applyPlan, job.id)");
    expect(server).toContain("saveCompletedBimJobCache");
    expect(server).toContain("loadActiveReusableBimJob");
    expect(server).toContain("insertBimJobLogByUid");
    expect(server).toContain("shouldReuseActiveBimJob");
    expect(server).toContain("withBimJobCreationLock");
    expect(readRepoFile("src/application/budget/bim-job-cache-domain.mjs")).toContain("const hasVersionedModelIdentity");
    expect(readRepoFile("src/application/budget/bim-job-cache-domain.mjs")).toContain("documentRevision");
    expect(server).toContain("buildBimJobCreationLockName");
    expect(server).toContain("GET_LOCK");
    expect(server).toContain("RELEASE_LOCK");
    expect(server).toContain("BIM_JOB_CREATE_LOCK_TIMEOUT");
    expect(server).toContain("MTRD_BimJob_ClaimedAt AS claimed_at");
    expect(server).toContain("queueWaitSeconds");
    expect(server).toContain("runSeconds");
    expect(server).toContain("totalSeconds");
    expect(server).toContain("diffIsoSeconds");
    expect(server).toContain("Solicitud duplicada reutilizo este job activo");
    expect(server).toContain("BIM_JOB_ACTIVE_REUSE_STATUSES");
    expect(server).toContain("bim-job-cache-domain.mjs");
    expect(server).toContain("buildBimJobCacheKeyDomain");
    expect(server).toContain("shouldPersistBimJobCache");
    expect(server).toContain("bim-job-stale-domain.mjs");
    expect(server).toContain("createBimJobStaleExpirationPlan");
    expect(server).toContain("expireStaleBimJobs");
    expect(server).toContain("BIM_JOB_STALE_MINUTES");
    expect(server).toContain("text/event-stream");
    expect(server).toContain("BIM_JOB_SSE_POLL_MS");
    expect(server).toContain("BIM_JOB_SSE_RETRY_MS");
    expect(server).toContain("bim-job-events-domain.mjs");
    expect(server).toContain("shouldEmitBimJobSseUpdate(job, lastSignature)");
    expect(server).toContain("if (closed) {\n    return;\n  }\n  const interval");
    expect(jobEventsDomain).toContain("normalizePercent(job.percent)");
    expect(jobEventsDomain).toContain("createResultSignature(job.result)");
    expect(server).toContain("event: ${event}");
    expect(server).toContain("writeEvent(\"ping\"");
    expect(server).toContain("retry: ${BIM_JOB_SSE_RETRY_MS}");
    expect(workspace).toContain("source.addEventListener(\"ping\"");
    expect(workspace).toContain("if (!data)");
    expect(workspace).toContain("selectBimJobsForRealtime");
    expect(workspace).toContain("pendingJobs = new Map<string, BimJobRecord>()");
    expect(workspace).toContain("flushTimers = new Map<string, number>()");
    expect(workspace).toContain("BIM_JOB_REALTIME_FLUSH_MS");
    expect(workspace).toContain("getBimJobFluencyMetrics");
    expect(workspace).toContain("bim-job-fluency");
    expect(workspace).toContain("bim-job-fluency--");
    expect(workspace).toContain("formatBimJobFluencyMetrics");
    expect(workspace).toContain("getBimJobFluencyLabel");
    expect(styles).toContain(".bim-job-fluency");
    expect(styles).toContain(".bim-job-fluency--warning");
    expect(styles).toContain(".bim-job-fluency--critical");
    expect(bimJobsDomain).toContain("BIM_JOB_REALTIME_MAX_STREAMS = 4");
    expect(bimJobsDomain).toContain("planBimJobRealtimePanelCommits");
    expect(bimJobsDomain).toContain("summarizeBimJobRealtimePanelLoad");
    expect(bimJobsDomain).toContain("withinCommitBudget");
    expect(bimJobsDomain).toContain("renderReductionPercent");
    expect(bimJobsDomain).toContain("getBimJobFluencyMetrics");
    expect(bimJobsDomain).toContain("BIM_JOB_FLUENCY_WARNING_MS = 750");
    expect(bimJobsDomain).toContain("BIM_JOB_FLUENCY_CRITICAL_MS = 2000");
    expect(apiSmoke).toContain("requestFirstSseJobEvent");
    expect(apiSmoke).toContain("text/event-stream");
    expect(apiSmoke).toContain("queueWaitSeconds");
    expect(apiSmoke).toContain("totalSeconds");
    expect(bridgeE2eSmoke).toContain("ownership-mismatch");
    expect(bridgeE2eSmoke).toContain("artifact-before-claim");
    expect(bridgeE2eSmoke).toContain("artifact-ownership-mismatch");
    expect(bridgeE2eSmoke).toContain("BIM_JOB_OWNERSHIP_MISMATCH");
    expect(bridgeE2eSmoke).toContain("statusCode === 409");
    expect(bridgeE2eSmoke).toContain("requestedBy: config.requestedBy");
    expect(bridgeE2eSmoke).toContain("expectMissingRequestedByRejected");
    expect(bridgeE2eSmoke).toContain("BIM_BRIDGE_SIGNED_USER_REQUIRED");
    expect(cloudWorker).toContain("recordCloudWorkerBatchTelemetry");
    expect(cloudWorker).toContain("createBatchProgress(plan, batchIndex");
    expect(cloudWorker).toContain("yieldDelayMs: config.batchDelayMs");
    expect(cloudWorker).toContain("result: progress.result");
    expect(cloudWorkerDomain).toContain("CLOUD_WORKER_FLUENCY_WARNING_MS = 750");
    expect(cloudWorkerDomain).toContain("CLOUD_WORKER_FLUENCY_CRITICAL_MS = 2000");
    expect(cloudWorkerDomain).toContain("createCloudWorkerBatchTelemetry");
    expect(cloudWorkerDomain).toContain("recordCloudWorkerBatchTelemetry");
    expect(cloudWorkerDomain).toContain("resolveCloudWorkerFluencyStatus");
    expect(cloudWorkerDomain).toContain("plannedBatches");
    expect(cloudWorkerDomain).toContain("fluencyStatus");
    expect(packageJson).toContain("bim:realtime-load-test");
    expect(packageJson).toContain("bim:fluency-check");
    expect(packageJson).toContain("bim:prepare-smoke");
    expect(packageJson).toContain("revit:bim-batch-plan");
    expect(packageJson).toContain("revit:bim-bridge-backoff");
    expect(packageJson).toContain("bim:readiness");
    expect(packageJson).toContain("worker:bim:list-activities");
    expect(realtimeLoadTest).toContain("runBimRealtimeLoadTest");
    expect(realtimeLoadTest).toContain("renderReductionPercent");
    expect(realtimeLoadTest).toContain("withinCommitBudget");
    expect(realtimeLoadTest).toContain("terminalCommitCount");
    expect(fluencyCheck).toContain("runBimCloudLoadTest");
    expect(fluencyCheck).toContain("runBimRealtimeLoadTest");
    expect(fluencyCheck).toContain("runRevitBridgeBackoffProbe");
    expect(fluencyCheck).toContain("runRevitTransactionFailureProbe");
    expect(fluencyCheck).toContain("--bim-batch-plan");
    expect(fluencyCheck).toContain("--bim-bridge-backoff");
    expect(fluencyCheck).toContain("--bim-transaction-failure");
    expect(fluencyCheck).toContain("--json");
    expect(fluencyCheckDomain).toContain("createBimFluencyCheckReport");
    expect(fluencyCheckDomain).toContain("normalizeRevitBatchPlanProbe");
    expect(fluencyCheckDomain).toContain("normalizeRevitBridgeBackoffProbe");
    expect(fluencyCheckDomain).toContain("normalizeRevitTransactionFailureProbe");
    expect(smokeConfig).toContain("api/auth/web/session");
    expect(smokeConfig).toContain("api/state");
    expect(smokeConfig).toContain("createBimLocalEnvPatch");
    expect(smokeConfigDomain).toContain("createBimSmokeConfigPlan");
    expect(smokeConfigDomain).toContain("EDITOR_SESSION");
    expect(revitBenchmarkProject).toContain("RevitModelAudit.Core.csproj");
    expect(revitBenchmarkProgram).toContain("--bim-batch-plan");
    expect(revitBenchmarkProgram).toContain("--bim-bridge-backoff");
    expect(revitBenchmarkProgram).toContain("--bim-transaction-failure");
    expect(revitBenchmarkProgram).toContain("--json");
    expect(revitBenchmarkProgram).toContain("RunBimBatchPlanProbe");
    expect(revitBenchmarkProgram).toContain("RunBimBridgeBackoffProbe");
    expect(revitBenchmarkProgram).toContain("RunBimTransactionFailureProbe");
    expect(revitBenchmarkProgram).toContain("BimJobBatchPlanner.CreatePlan");
    expect(revitBenchmarkProgram).toContain("BimJobBridgeBackoffPlanner.ResolveClaimFailureBackoffSeconds");
    expect(revitBenchmarkProgram).toContain("BimJobCancellationProbePolicy.Resolve");
    expect(revitBenchmarkProgram).toContain("CancellationProbeCount");
    expect(revitBenchmarkProgram).toContain("YieldCount");
    expect(revitBridgeBackoffPlanner).toContain("MinClaimFailureBackoffSeconds = 15");
    expect(revitBridgeBackoffPlanner).toContain("MaxClaimFailureBackoffSeconds = 300");
    expect(readiness).toContain("createBimReadinessReport");
    expect(readiness).toContain("createBimReadinessRuntimeReport");
    expect(readiness).toContain("ITEMICOSTOS_BACKEND_HEALTH");
    expect(readiness).toContain("backendHealthReady");
    expect(readiness).toContain("bim-fluency-gate");
    expect(readiness).toContain("localFluencyReady");
    expect(readiness).toContain("BIM_FLUENCY_CHECK_REPORT");
    expect(readiness).toContain("revit-cancellation-probe");
    expect(readiness).toContain("revit-transaction-failure");
    expect(readRepoFile("src/application/budget/bim-readiness-api-domain.mjs")).toContain("createBackendBimReadinessSnapshot");
    expect(readiness).toContain("readyForRealValidation");
    expect(readiness).toContain("active-revit-e2e-smoke");
    expect(readiness).toContain("active-revit-bridge-presence-runtime");
    expect(readiness).toContain("active-revit-bridge-claim-runtime");
    expect(readiness).toContain("ACTIVE_REVIT_GOOGLE_SIGN_IN");
    expect(readiness).toContain("ACTIVE_REVIT_BRIDGE_PRESENCE");
    expect(readiness).toContain("revit-local-session-runtime");
    expect(readRepoFile("workers/bim-readiness.mjs")).toContain("BIM_READINESS_CHECK_REVIT_SESSION");
    expect(readiness).toContain("requestedByConfigured");
    expect(readRepoFile("package.json")).toContain("bim:revit-session");
    expect(readRepoFile("workers/bim-revit-local-session-domain.mjs")).toContain("REVIT_ADDIN_RESTART_REQUIRED");
    expect(readiness).toContain("aps-design-automation");
    expect(bridgeAccessDomain).toContain("BIM_BRIDGE_SIGNED_USER_REQUIRED");
    expect(bridgeAccessDomain).toContain("BIM_BRIDGE_PROJECT_FORBIDDEN");
  });

  it("keeps the Revit bridge guarded against wrong active models", () => {
    const runner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobExternalEventRunner.cs");
    const guard = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobModelIdentityGuard.cs");

    expect(runner).toContain("BimJobModelIdentityGuard.Validate");
    expect(runner).toContain("Modelo incorrecto");
    expect(runner).toContain("actualModelIdentity");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("AddModelIdentityQuery");
    expect(guard).toContain("modelGuid");
    expect(guard).toContain("documentUid");
    expect(guard).toContain("documentVersion");
    expect(guard).toContain("ResolveDocumentVersion");
    expect(guard).toContain("modelPath");
  });

  it("keeps BIM worker finalization from winning over cancelled or finished jobs", () => {
    const server = readRepoFile("server.js");
    const worker = readRepoFile("workers/bim-cloud-worker.mjs");
    const jobStateDomain = readRepoFile("src/application/budget/bim-job-state-domain.mjs");

    const terminalProgressGuard = "const progressDecision = createBimJobProgressDecision(row.status_name)";
    const progressStatusUpdate = "const progressUpdate = normalizeIncomingBimJobProgress(progress";
    expect(server).toContain(terminalProgressGuard);
    expect(server.indexOf(terminalProgressGuard))
      .toBeLessThan(server.indexOf(progressStatusUpdate));
    expect(server).toContain("currentStatus: progressDecision.currentStatus || \"running\"");
    expect(jobStateDomain).toContain("createBimJobProgressDecision");
    expect(jobStateDomain).toContain("se ignora el progreso tardio");
    expect(readRepoFile("src/application/budget/bim-job-command-domain.mjs")).toContain("resolveBimJobProgressStatus");
    expect(server).toContain("return this.loadBimJob(jobUid)");
    expect(server).toContain("No se pueden registrar artefactos en un job BIM finalizado");
    expect(server).toContain("No se pueden registrar operaciones en un job BIM finalizado");
    expect(server).toContain("MTRD_BimJob_Status AS status_name");
    expect(server).toContain("FOR UPDATE");
    expect(server).toContain("isFinishedBimJobStatus(jobRows[0]?.status_name)");
    expect(server).toContain("isFinishedBimJobStatus(row.status_name)");
    expect(worker).toContain("error.statusCode === 409");
    expect(worker).toContain("termino antes de registrar artefactos");
  });

  it("keeps confirmed Revit apply jobs isolated in small batch transactions", () => {
    const runner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobExternalEventRunner.cs");
    const batchPlanner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobBatchPlanner.cs");
    const transactionFailurePolicy = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobApplyTransactionFailurePolicy.cs");
    const remoteStopPolicy = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobRemoteStopPolicy.cs");
    const progressReportPolicy = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobProgressReportPolicy.cs");
    const revitBenchmarkProgram = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Benchmarks/Program.cs");

    expect(runner).toContain("BimJobBatchPlanner.CreatePlan");
    expect(runner).toContain("BimJobBatchPlanner.ResolveBatchEndIndex");
    expect(runner).toContain("BimJobBatchPlanner.RevitYieldDelayMs");
    expect(runner).toContain("plannedBatches");
    expect(runner).toContain("plannedCancellationChecks");
    expect(runner).toContain("yieldDelayMs");
    expect(runner).toContain("BatchTelemetry.RecordBatch");
    expect(runner).toContain("lastBatchDurationMs");
    expect(runner).toContain("averageBatchDurationMs");
    expect(runner).toContain("maxBatchDurationMs");
    expect(runner).toContain("totalBatchDurationMs");
    expect(runner).toContain("fluencyStatus");
    expect(runner).toContain("cancellationProbeFailures");
    expect(runner).toContain("lastCancellationProbeError");
    expect(runner).toContain("BimJobCancellationProbePolicy.Resolve");
    expect(runner).toContain("BimJobRemoteStopPolicy.Resolve(latestJob.Status, current.Request.Job.Id)");
    expect(runner).toContain("BimJobProgressReportPolicy.ResolveRemoteStop");
    expect(runner).toContain("BimJobRemoteTerminalStopException");
    expect(runner).toContain("StopBecauseRemoteTerminal");
    expect(remoteStopPolicy).toContain("\"cancelled\"");
    expect(remoteStopPolicy).toContain("\"failed\"");
    expect(remoteStopPolicy).toContain("\"completed\"");
    expect(progressReportPolicy).toContain("ResolveRemoteStop");
    expect(progressReportPolicy).toContain("normalizedRequested");
    expect(revitBenchmarkProgram).toContain("RemoteStopCases");
    expect(revitBenchmarkProgram).toContain("ProgressReportCases");
    expect(revitBenchmarkProgram).toContain("OperationPageCases");
    expect(revitBenchmarkProgram).toContain("CreateProgressReportProbeCase");
    expect(revitBenchmarkProgram).toContain("CreateOperationPageProbeCase");
    expect(runner).toContain("ShouldAbortBeforeNextBatch");
    expect(runner).toContain("Level = current.BatchTelemetry.FluencyStatus == \"ok\" && !cancellationProbeDecision.ShouldWarn ? \"info\" : \"warn\"");
    expect(batchPlanner).toContain("DefaultBatchSize = 250");
    expect(batchPlanner).toContain("MinBatchSize = 25");
    expect(batchPlanner).toContain("MaxBatchSize = 5000");
    expect(batchPlanner).toContain("RevitYieldDelayMs = 25");
    expect(batchPlanner).toContain("SlowBatchWarningMs = 750");
    expect(batchPlanner).toContain("SlowBatchCriticalMs = 2000");
    expect(batchPlanner).toContain("CancellationProbeCount => BatchCount");
    expect(batchPlanner).toContain("BimJobBatchTelemetry");
    expect(batchPlanner).toContain("AverageBatchDurationMs");
    expect(batchPlanner).toContain("ResolveFluencyStatus");
    expect(runner).toContain("TryProcessApplyBatch");
    expect(runner).toContain("new Transaction");
    expect(runner).toContain("TransactionStatus.Started");
    expect(runner).toContain("TransactionStatus.Committed");
    expect(runner).toContain("RollBackOpenTransaction");
    expect(runner).toContain("BimJobApplyTransactionFailurePolicy.Resolve");
    expect(runner).toContain("failure.ToTelemetry()");
    expect(transactionFailurePolicy).toContain("Error de transaccion");
    expect(transactionFailurePolicy).toContain("apply-transaction-failure");
    expect(transactionFailurePolicy).toContain("failedBatchOperationCount");
    expect(transactionFailurePolicy).toContain("committedApplyBatchesBeforeFailure");
    expect(runner).toContain("applyTransactionMode");
    expect(runner).toContain("BuildApplyPlan");
    expect(runner).toContain("TryUploadApplyPlanOperations");
    expect(runner).toContain("ApplyPlanOperationUploadPageSize = 1000");
    expect(runner).toContain("BimJobOperationPagePlanner.CreateUploadPlan");
    expect(runner).toContain("HasExecutableApplyPlan");
    expect(runner).toContain("Apply plan invalido");
    expect(runner).toContain("[\"applyPlan\"] = applyPlan");
    expect(runner).toContain("plan[\"operationsSource\"] = operationsSource");
    expect(runner).toContain("[\"operationType\"] = \"parameter-write\"");
    expect(runner).toContain("[\"operationCount\"] = operations.Count");
    expect(runner).toContain("[\"operations\"] = operations.Select(operation => operation.ToPayload()).ToList()");
    expect(runner).toContain("LoadParameterWriteOperationsFromSource");
    expect(runner).toContain("TryReadOperationsSourceDescriptor");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("LoadOperations");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("UploadOperations");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("LoadBridgeSummary");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("revit-local-session-runtime");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs")).toContain("active-revit-bridge-presence-runtime");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Commands/ProcessBimJobsCommand.cs")).toContain("TryBuildBridgeSummaryFooter");
    expect(readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Commands/ProcessBimJobsCommand.cs")).toContain("Cola Revit Itemicostos");
    expect(runner).toContain("ResolveWritableParameter(document, element, operation.ParameterName)");
    expect(runner).toContain("GetElementType(document, element)");
    expect(runner).toContain("CommittedApplyBatches");
  });

  it("keeps Revit bridge progress reporting failures from trapping the runner", () => {
    const runner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobExternalEventRunner.cs");

    expect(runner).toContain("BimJobProgressReportException");
    expect(runner).toContain("Perdida de red");
    expect(runner).toContain("TryReportProgress");
    expect(runner).toContain("LastProgressReportError");
    expect(runner).toContain("backend resolvera el job por heartbeat");
    expect(runner).toContain("backend marcara el job por heartbeat");
  });

  it("keeps the Revit bridge able to claim jobs automatically without bypassing ExternalEvent", () => {
    const app = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/App.cs");
    const autoBridge = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobAutoBridgeService.cs");
    const runner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobExternalEventRunner.cs");
    const readiness = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Jobs/BimJobBridgeReadinessReport.cs");
    const settings = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosMetradoExportModels.cs");
    const command = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Commands/ProcessBimJobsCommand.cs");
    const backoffPlanner = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Core/Services/BimJobBridgeBackoffPlanner.cs");

    expect(app).toContain("application.Idling += OnApplicationIdling");
    expect(app).toContain("application.Idling -= OnApplicationIdling");
    expect(autoBridge).toContain("Task.Run(() => ClaimJob");
    expect(autoBridge).toContain("request.RequestedBy");
    expect(autoBridge).toContain("BimJobBridgeReadinessReport.Create");
    expect(autoBridge).toContain("readiness.CanAutoClaimJobs");
    expect(autoBridge).toContain("TryStartDiagnosticHeartbeat");
    expect(autoBridge).toContain("ReportBridgeHeartbeat");
    expect(autoBridge).toContain("BimJobExternalEventRunner.Start");
    expect(autoBridge).toContain("BimJobExternalEventRunner.IsBusy");
    expect(autoBridge).toContain("RegisterClaimFailure");
    expect(autoBridge).toContain("ResetClaimFailureBackoff");
    expect(autoBridge).toContain("BimJobBridgeBackoffPlanner.ResolveClaimFailureBackoffSeconds");
    expect(backoffPlanner).toContain("ResolveClaimFailureBackoffSeconds");
    expect(backoffPlanner).toContain("MaxClaimFailureBackoffSeconds = 300");
    expect(autoBridge).toContain("GoogleSignInSessionStore.TryGetValidSession");
    expect(readiness).toContain("ValidateForBimBridge");
    expect(runner).toContain("public static bool IsBusy");
    expect(command).toContain("BimJobBridgeReadinessReport.Create");
    expect(command).toContain("readiness.BuildDialogMessage");
    expect(command).toContain("readiness.ActiveModelIdentity");
    expect(readiness).toContain("Readiness BIM");
    expect(readiness).toContain("web.ingestApiKey");
    expect(readiness).toContain("ActiveModelIdentity");
    expect(readiness).toContain("AutoClaimEnabled");
    expect(readiness).toContain("BuildHeartbeatDiagnostic");
    expect(readiness).toContain("RunnerBusy");
    expect(settings).toContain("AutoClaimBimJobs");
    expect(settings).toContain("BimJobPollSeconds");
    expect(settings).toContain("REVIT_INGEST_API_KEY");
  });

  it("keeps Revit BIM job claims tied to the signed-in Google user for traceability", () => {
    const command = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Commands/ProcessBimJobsCommand.cs");
    const bridgeService = readRepoFile("../REVIT-MODEL-AUDITOR/src/RevitModelAudit.Revit/Importing/ItemicostosBimJobBridgeService.cs");
    const server = readRepoFile("server.js");

    expect(command).toContain("GoogleCommandAccessGuard.EnsureSignedIn");
    expect(command).toContain("signedInSession.Email");
    expect(bridgeService).toContain("requestedBy");
    expect(bridgeService).toContain("requestedBy={Uri.EscapeDataString(requestedBy.Trim())}");
    expect(bridgeService).toContain("documentVersion");
    expect(server).toContain("url.searchParams.get(\"requestedBy\")");
    expect(server).toContain("findUserByEmail(requestedBy)");
    expect(readRepoFile("src/application/budget/bim-bridge-access-domain.mjs")).toContain("BIM_BRIDGE_USER_NOT_AUTHORIZED");
    expect(server).toContain("Usuario Revit");
  });
});
